spring:
  application:
    name: backend_oscar

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_db
    username: crypto_user
    password: crypto_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


